QT += quick
QT += gui
QT += serialport
QT += charts
QT += concurrent
CONFIG += c++11
CONFIG += console

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Refer to the documentation for the
# deprecated API to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# disable C4819 warning
QMAKE_CXXFLAGS_WARN_ON += -wd4819
QMAKE_CXXFLAGS_WARN_ON += -wd4100

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        Commands/audio_command.cpp \
        Commands/bubblecalibrate_command.cpp \
        Commands/bubblegetcount_command.cpp \
        Commands/bubblemeasureflighttime_command.cpp \
        Commands/bubblemeasurevolume_command.cpp \
        Commands/bubblestopmeasureflighttime_command.cpp \
        Commands/bubblewatchsensors_command.cpp \
        Commands/camera_command.cpp \
        Commands/cameraenablezsettling_command.cpp \
        Commands/camerapenalty_command.cpp \
        Commands/camerareadleddata_command.cpp \
        Commands/camerareadledgains_command.cpp \
        Commands/camerasetaf_command.cpp \
        Commands/camerasnap_command.cpp \
        Commands/camerasnapfree_command.cpp \
        Commands/camerasnapfreeall_command.cpp \
        Commands/camerastoreledgains_command.cpp \
        Commands/cancel_command.cpp \
        Commands/cancelbyid_command.cpp \
        Commands/command.cpp \
        Commands/cpqcihack_command.cpp \
        Commands/fangetppm_command.cpp \
        Commands/fanonoff_command.cpp \
        Commands/fanthermalcontrol_command.cpp \
        Commands/flowcelldoorclose_command.cpp \
        Commands/flowcelldoorgetsealdistance_command.cpp \
        Commands/flowcelldoorgetstate_command.cpp \
        Commands/flowcelldooropen_command.cpp \
        Commands/flowcelldoorsetsealdistance_command.cpp \
        Commands/fluidicsautomationbufferpresentcontrol_command.cpp \
        Commands/fluidicsautomationdo_command.cpp \
        Commands/fluidicsautomationgetpos_command.cpp \
        Commands/fluidicsautomationmovetoy_command.cpp \
        Commands/fluidicsautomationreagenttrayctrl_command.cpp \
        Commands/getinterfacesignature_command.cpp \
        Commands/humidityread_command.cpp \
        Commands/loggetlist_command.cpp \
        Commands/logreplay_command.cpp \
        Commands/miscfwids_command.cpp \
        Commands/miscfwidstr_command.cpp \
        Commands/miscfwstage_command.cpp \
        Commands/motionmove_command.cpp \
        Commands/motionreadencoder_command.cpp \
        Commands/motionservohistory_command.cpp \
        Commands/pressuresensorread_command.cpp \
        Commands/pump_command.cpp \
        Commands/pumpabsorb_command.cpp \
        Commands/pumpdispense_command.cpp \
        Commands/pumpinit_command.cpp \
        Commands/pumpwrite_command.cpp \
        Commands/rfidtagget_command.cpp \
        Commands/rfidtaggetstatus_command.cpp \
        Commands/rfidtagreset_command.cpp \
        Commands/rfidtagset_command.cpp \
        Commands/rfidtagvalidation_command.cpp \
        Commands/sampleheatercalculatepoint_command.cpp \
        Commands/sampleheatercalculatepoints_command.cpp \
        Commands/sampleheatercalculatereset_command.cpp \
        Commands/sampleheaterdisable_command.cpp \
        Commands/sampleheaterenable_command.cpp \
        Commands/sampleheatertargetget_command.cpp \
        Commands/sampleheatertargetset_command.cpp \
        Commands/sampleheatertemperature_command.cpp \
        Commands/sensoroverride_command.cpp \
        Commands/sensorposition_command.cpp \
        Commands/sensorread_command.cpp \
        Commands/settingsflush_command.cpp \
        Commands/settingsget_command.cpp \
        Commands/settingsgetkeynames_command.cpp \
        Commands/settingsset_command.cpp \
        Commands/shutdownispoweroff_command.cpp \
        Commands/shutdownisreset_command.cpp \
        Commands/systemled_command.cpp \
        Commands/timegetmsec_command.cpp \
        Commands/timesetclock_command.cpp \
        Commands/valvegetposition_command.cpp \
        Commands/valvewrite_command.cpp \
        Commands/xy_command.cpp \
        Commands/xyemergencystop_commmand.cpp \
        Commands/xyenablerangecheck_command.cpp \
        Commands/xyfindzero_command.cpp \
        Commands/xygetpositions_command.cpp \
        Commands/xyhand_command.cpp \
        Commands/xyhealthy_command.cpp \
        Commands/xyinit_command.cpp \
        Commands/xymoveto_command.cpp \
        Commands/xymovetohomepoint_command.cpp \
        Commands/xymovetosequencepoint_command.cpp \
        Commands/xymovetoship_command.cpp \
        Commands/xyoffsets_command.cpp \
        Commands/xyreinitialize_command.cpp \
        Commands/xyselfinspection_command.cpp \
        Commands/xysetminmovemsec_command.cpp \
        Commands/xysetsettlemsec_command.cpp \
        Commands/xystatus_command.cpp \
        Commands/xytargetgo_command.cpp \
        Commands/xytargetset_command.cpp \
        Commands/xytargetsset_command.cpp \
        Commands/zstagegetheight_command.cpp \
        Commands/zstageinitialize_command.cpp \
        Commands/zstageisready_command.cpp \
        Commands/zstagesetheight_command.cpp \
        Commands/zstagewatchheight_command.cpp \
        Core/serialportcore.cpp \
        Responses/audio_command_response.cpp \
        Responses/bubblecalibrate_command_response.cpp \
        Responses/bubblegetcount_command_response.cpp \
        Responses/bubblemeasureflighttime_command_response.cpp \
        Responses/bubblewatchrecord_command_response.cpp \
        Responses/bubblewatchsensors_command_response.cpp \
        Responses/camera_command_response.cpp \
        Responses/cameraenablezsettling_command_response.cpp \
        Responses/cameraevent_command_response.cpp \
        Responses/camerapenalty_command_response.cpp \
        Responses/camerareadleddata_command_response.cpp \
        Responses/camerareadledgain_command_response.cpp \
        Responses/camerasetaf_command_response.cpp \
        Responses/camerasnap_command_response.cpp \
        Responses/camerasnapfree_command_response.cpp \
        Responses/camerasnapfreeall_command_response.cpp \
        Responses/camerastoreledgains_command_response.cpp \
        Responses/cancel_command_response.cpp \
        Responses/error_nofification.cpp \
        Responses/fangetppm_command_response.cpp \
        Responses/fanonoff_command_response.cpp \
        Responses/fanthermalcontrol_command_response.cpp \
        Responses/flowcelldoorclose_command_response.cpp \
        Responses/flowcelldoorgetsealdistance_command_response.cpp \
        Responses/flowcelldoorgetstate_command_response.cpp \
        Responses/flowcelldooropen_command_response.cpp \
        Responses/flowcelldoorsetsealdistance_command_response.cpp \
        Responses/fluidicsautomationdo_command_response.cpp \
        Responses/fluidicsautomationgetpos_command_response.cpp \
        Responses/fluidicsautomationnull_command_response.cpp \
        Responses/getinterfacesignature_command_response.cpp \
        Responses/humidityread_command_response.cpp \
        Responses/loggetlist_command_response.cpp \
        Responses/logrecord_command_response.cpp \
        Responses/logreplay_command_response.cpp \
        Responses/miscfwids_command_response.cpp \
        Responses/miscfwidstr_command_response.cpp \
        Responses/miscfwstage_command_response.cpp \
        Responses/motionmove_command_response.cpp \
        Responses/motionnotify_command_response.cpp \
        Responses/motionreadencoder_command_response.cpp \
        Responses/motionservohistory_command_response.cpp \
        Responses/motionservorec_command_response.cpp \
        Responses/pressuresensorread_command_response.cpp \
        Responses/pumpabsorb_command_response.cpp \
        Responses/pumpdata_command_response.cpp \
        Responses/pumpdispense_command_response.cpp \
        Responses/pumpinit_command_response.cpp \
        Responses/pumpwrite_command_response.cpp \
        Responses/response.cpp \
        Responses/rfidtag_command_response.cpp \
        Responses/rfidtagget_command_response.cpp \
        Responses/rfidtaggetstatus_command_response.cpp \
        Responses/rfidtagreset_command_response.cpp \
        Responses/rfidtagset_command_response.cpp \
        Responses/rfidtagvalidation_command_response.cpp \
        Responses/sampleheatercalculatepoint_command_response.cpp \
        Responses/sampleheatercalculatepoints_command_response.cpp \
        Responses/sampleheatercalculatereset_command_response.cpp \
        Responses/sampleheaterconnected_command_response.cpp \
        Responses/sampleheaterdisable_command_response.cpp \
        Responses/sampleheaterenable_command_response.cpp \
        Responses/sampleheatertargetget_command_response.cpp \
        Responses/sampleheatertargetset_command_response.cpp \
        Responses/sampleheatertemperature_command_response.cpp \
        Responses/sensornotify_command_response.cpp \
        Responses/sensoroverride_command_response.cpp \
        Responses/sensorposition_command_response.cpp \
        Responses/sensorpositionrecord_command_response.cpp \
        Responses/sensorread_command_response.cpp \
        Responses/settingsget_command_response.cpp \
        Responses/settingsgetkeynames_command_response.cpp \
        Responses/settingsvoid_command_response.cpp \
        Responses/settinsvoid_command_response.cpp \
        Responses/shutdownis_command_response.cpp \
        Responses/systemled_command_response.cpp \
        Responses/timegetmsec_command_response.cpp \
        Responses/timesetclock_command_response.cpp \
        Responses/valvedata_command_response.cpp \
        Responses/valvewrite_command_response.cpp \
        Responses/xyemergencystop_commmand_response.cpp \
        Responses/xyenablerangecheck_command_response.cpp \
        Responses/xyfindzero_command_response.cpp \
        Responses/xygetposition_command_response.cpp \
        Responses/xyhand_command_response.cpp \
        Responses/xyhealthy_command_response.cpp \
        Responses/xyinit_command_response.cpp \
        Responses/xymoveto_command_response.cpp \
        Responses/xymovetohomepoint_command_response.cpp \
        Responses/xymovetosequencepoint_command_response.cpp \
        Responses/xymovetoship_command_response.cpp \
        Responses/xyoffset_command_response.cpp \
        Responses/xyreinitialize_command_response.cpp \
        Responses/xyselfinspection_command_response.cpp \
        Responses/xysetminmovemsec_command_response.cpp \
        Responses/xysetsettlemsec_command_response.cpp \
        Responses/xystatus_command_response.cpp \
        Responses/xytargetgo_command_response.cpp \
        Responses/xytargetset_command_response.cpp \
        Responses/zstagegetheight_command_response.cpp \
        Responses/zstagegetheightresult_command_response.cpp \
        Responses/zstageinitialize_command_response.cpp \
        Responses/zstageisready_command_response.cpp \
        Responses/zstagesetheight_command_response.cpp \
        Responses/zstagewatchheight_command_response.cpp \
        Tools/applicationexception.cpp \
        Tools/grayimage.cpp \
        Tools/imagebase.cpp \
        Tools/imagechangedeventargs.cpp \
        Tools/imagesizechangedeventargs.cpp \
        Tools/indexoutofrangeexception.cpp \
        Tools/normalexception.cpp \
        Tools/nullexception.cpp \
        communicationcore.cpp \
        globals/globalSet.cpp \
        globals/qmlaggregator.cpp \
        instrumentoperator.cpp \
        main.cpp \
        models/bubblemeasureflighttimemeasuremodel.cpp \
        models/debug/pumptestmodel.cpp \
        operators/bubblemeasureflighttimeoperaotr.cpp \
        operators/debugs/pressureinspection_instrumentoperator.cpp \
        operators/debugs/pumptest_instrumentoperator.cpp \
        operators/status_instrumentoperator.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    Commands/audio_command.h \
    Commands/bubblecalibrate_command.h \
    Commands/bubblegetcount_command.h \
    Commands/bubblemeasureflighttime_command.h \
    Commands/bubblemeasurevolume_command.h \
    Commands/bubblestopmeasureflighttime_command.h \
    Commands/bubblewatchsensors_command.h \
    Commands/camera_command.h \
    Commands/cameraenablezsettling_command.h \
    Commands/camerapenalty_command.h \
    Commands/camerareadleddata_command.h \
    Commands/camerareadledgains_command.h \
    Commands/camerasetaf_command.h \
    Commands/camerasnap_command.h \
    Commands/camerasnapfree_command.h \
    Commands/camerasnapfreeall_command.h \
    Commands/camerastoreledgains_command.h \
    Commands/cancel_command.h \
    Commands/cancelbyid_command.h \
    Commands/command.h \
    Commands/cpqcihack_command.h \
    Commands/fangetppm_command.h \
    Commands/fanonoff_command.h \
    Commands/fanthermalcontrol_command.h \
    Commands/flowcelldoorclose_command.h \
    Commands/flowcelldoorgetsealdistance_command.h \
    Commands/flowcelldoorgetstate_command.h \
    Commands/flowcelldooropen_command.h \
    Commands/flowcelldoorsetsealdistance_command.h \
    Commands/fluidicsautomationbufferpresentcontrol_command.h \
    Commands/fluidicsautomationdo_command.h \
    Commands/fluidicsautomationgetpos_command.h \
    Commands/fluidicsautomationmovetoy_command.h \
    Commands/fluidicsautomationreagenttrayctrl_command.h \
    Commands/getinterfacesignature_command.h \
    Commands/humidityread_command.h \
    Commands/loggetlist_command.h \
    Commands/logreplay_command.h \
    Commands/miscfwids_command.h \
    Commands/miscfwidstr_command.h \
    Commands/miscfwstage_command.h \
    Commands/motionmove_command.h \
    Commands/motionreadencoder_command.h \
    Commands/motionservohistory_command.h \
    Commands/pressuresensorread_command.h \
    Commands/pump_command.h \
    Commands/pumpabsorb_command.h \
    Commands/pumpdispense_command.h \
    Commands/pumpinit_command.h \
    Commands/pumpwrite_command.h \
    Commands/rfidtagget_command.h \
    Commands/rfidtaggetstatus_command.h \
    Commands/rfidtagreset_command.h \
    Commands/rfidtagset_command.h \
    Commands/rfidtagvalidation_command.h \
    Commands/sampleheatercalculatepoint_command.h \
    Commands/sampleheatercalculatepoints_command.h \
    Commands/sampleheatercalculatereset_command.h \
    Commands/sampleheaterdisable_command.h \
    Commands/sampleheaterenable_command.h \
    Commands/sampleheatertargetget_command.h \
    Commands/sampleheatertargetset_command.h \
    Commands/sampleheatertemperature_command.h \
    Commands/sensoroverride_command.h \
    Commands/sensorposition_command.h \
    Commands/sensorread_command.h \
    Commands/settingsflush_command.h \
    Commands/settingsget_command.h \
    Commands/settingsgetkeynames_command.h \
    Commands/settingsset_command.h \
    Commands/shutdownispoweroff_command.h \
    Commands/shutdownisreset_command.h \
    Commands/systemled_command.h \
    Commands/timegetmsec_command.h \
    Commands/timesetclock_command.h \
    Commands/valvegetposition_command.h \
    Commands/valvewrite_command.h \
    Commands/xy_command.h \
    Commands/xyemergencystop_commmand.h \
    Commands/xyenablerangecheck_command.h \
    Commands/xyfindzero_command.h \
    Commands/xygetpositions_command.h \
    Commands/xyhand_command.h \
    Commands/xyhealthy_command.h \
    Commands/xyinit_command.h \
    Commands/xymoveto_command.h \
    Commands/xymovetohomepoint_command.h \
    Commands/xymovetosequencepoint_command.h \
    Commands/xymovetoship_command.h \
    Commands/xyoffsets_command.h \
    Commands/xyreinitialize_command.h \
    Commands/xyselfinspection_command.h \
    Commands/xysetminmovemsec_command.h \
    Commands/xysetsettlemsec_command.h \
    Commands/xystatus_command.h \
    Commands/xytargetgo_command.h \
    Commands/xytargetset_command.h \
    Commands/xytargetsset_command.h \
    Commands/zstagegetheight_command.h \
    Commands/zstageinitialize_command.h \
    Commands/zstageisready_command.h \
    Commands/zstagesetheight_command.h \
    Commands/zstagewatchheight_command.h \
    Core/serialportcore.h \
    Responses/audio_command_response.h \
    Responses/bubblecalibrate_command_response.h \
    Responses/bubblegetcount_command_response.h \
    Responses/bubblemeasureflighttime_command_response.h \
    Responses/bubblewatchrecord_command_response.h \
    Responses/bubblewatchsensors_command_response.h \
    Responses/camera_command_response.h \
    Responses/cameraenablezsettling_command_response.h \
    Responses/cameraevent_command_response.h \
    Responses/camerapenalty_command_response.h \
    Responses/camerareadleddata_command_response.h \
    Responses/camerareadledgain_command_response.h \
    Responses/camerasetaf_command_response.h \
    Responses/camerasnap_command_response.h \
    Responses/camerasnapfree_command_response.h \
    Responses/camerasnapfreeall_command_response.h \
    Responses/camerastoreledgains_command_response.h \
    Responses/cancel_command_response.h \
    Responses/error_nofification.h \
    Responses/fangetppm_command_response.h \
    Responses/fanonoff_command_response.h \
    Responses/fanthermalcontrol_command_response.h \
    Responses/flowcelldoorclose_command_response.h \
    Responses/flowcelldoorgetsealdistance_command_response.h \
    Responses/flowcelldoorgetstate_command_response.h \
    Responses/flowcelldooropen_command_response.h \
    Responses/flowcelldoorsetsealdistance_command_response.h \
    Responses/fluidicsautomationdo_command_response.h \
    Responses/fluidicsautomationgetpos_command_response.h \
    Responses/fluidicsautomationnull_command_response.h \
    Responses/getinterfacesignature_command_response.h \
    Responses/humidityread_command_response.h \
    Responses/loggetlist_command_response.h \
    Responses/logrecord_command_response.h \
    Responses/logreplay_command_response.h \
    Responses/miscfwids_command_response.h \
    Responses/miscfwidstr_command_response.h \
    Responses/miscfwstage_command_response.h \
    Responses/motionmove_command_response.h \
    Responses/motionnotify_command_response.h \
    Responses/motionreadencoder_command_response.h \
    Responses/motionservohistory_command_response.h \
    Responses/motionservorec_command_response.h \
    Responses/pressuresensorread_command_response.h \
    Responses/pumpabsorb_command_response.h \
    Responses/pumpdata_command_response.h \
    Responses/pumpdispense_command_response.h \
    Responses/pumpinit_command_response.h \
    Responses/pumpwrite_command_response.h \
    Responses/response.h \
    Responses/rfidtag_command_response.h \
    Responses/rfidtagget_command_response.h \
    Responses/rfidtaggetstatus_command_response.h \
    Responses/rfidtagreset_command_response.h \
    Responses/rfidtagset_command_response.h \
    Responses/rfidtagvalidation_command_response.h \
    Responses/sampleheatercalculatepoint_command_response.h \
    Responses/sampleheatercalculatepoints_command_response.h \
    Responses/sampleheatercalculatereset_command_response.h \
    Responses/sampleheaterconnected_command_response.h \
    Responses/sampleheaterdisable_command_response.h \
    Responses/sampleheaterenable_command_response.h \
    Responses/sampleheatertargetget_command_response.h \
    Responses/sampleheatertargetset_command_response.h \
    Responses/sampleheatertemperature_command_response.h \
    Responses/sensornotify_command_response.h \
    Responses/sensoroverride_command_response.h \
    Responses/sensorposition_command_response.h \
    Responses/sensorpositionrecord_command_response.h \
    Responses/sensorread_command_response.h \
    Responses/settingsget_command_response.h \
    Responses/settingsgetkeynames_command_response.h \
    Responses/settingsvoid_command_response.h \
    Responses/settinsvoid_command_response.h \
    Responses/shutdownis_command_response.h \
    Responses/systemled_command_response.h \
    Responses/timegetmsec_command_response.h \
    Responses/timesetclock_command_response.h \
    Responses/valvedata_command_response.h \
    Responses/valvewrite_command_response.h \
    Responses/xyemergencystop_commmand_response.h \
    Responses/xyenablerangecheck_command_response.h \
    Responses/xyfindzero_command_response.h \
    Responses/xygetposition_command_response.h \
    Responses/xyhand_command_response.h \
    Responses/xyhealthy_command_response.h \
    Responses/xyinit_command_response.h \
    Responses/xymoveto_command_response.h \
    Responses/xymovetohomepoint_command_response.h \
    Responses/xymovetosequencepoint_command_response.h \
    Responses/xymovetoship_command_response.h \
    Responses/xyoffset_command_response.h \
    Responses/xyreinitialize_command_response.h \
    Responses/xyselfinspection_command_response.h \
    Responses/xysetminmovemsec_command_response.h \
    Responses/xysetsettlemsec_command_response.h \
    Responses/xystatus_command_response.h \
    Responses/xytargetgo_command_response.h \
    Responses/xytargetset_command_response.h \
    Responses/zstagegetheight_command_response.h \
    Responses/zstagegetheightresult_command_response.h \
    Responses/zstageinitialize_command_response.h \
    Responses/zstageisready_command_response.h \
    Responses/zstagesetheight_command_response.h \
    Responses/zstagewatchheight_command_response.h \
    Tools/applicationexception.h \
    Tools/grayimage.h \
    Tools/imagebase.h \
    Tools/imagechangedeventargs.h \
    Tools/imagesizechangedeventargs.h \
    Tools/indexoutofrangeexception.h \
    Tools/normalexception.h \
    Tools/nullexception.h \
    communicationcore.h \
    globals/enums.h \
    globals/globalSet.h \
    globals/onOff.h \
    globals/qmlaggregator.h \
    instrumentoperator.h \
    models/bubblemeasureflighttimemeasuremodel.h \
    models/debug/pumptestmodel.h \
    operators/bubblemeasureflighttimeoperaotr.h \
    operators/debugs/pressureinspection_instrumentoperator.h \
    operators/debugs/pumptest_instrumentoperator.h \
    operators/status_instrumentoperator.h
